// resources/js/Pages/Booking/Create.vue
<script setup lang="ts">
import InputError from '@/Components/InputError.vue';
import InputLabel from '@/Components/InputLabel.vue';
import PrimaryButton from '@/Components/PrimaryButton.vue';
import TextInput from '@/Components/TextInput.vue';
import { Head, Link, useForm } from '@inertiajs/vue3';
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout.vue';

const form = useForm({
  title: '',
  date: '',
});

const submit = () => {
  // dynamicaly post to update or store rout
  form.post(route('bookings.store'), {
    onSuccess: () => {
      form.reset();
    },
  });
};
</script>
<template>
  <Head title="Create Booking" />

  <AuthenticatedLayout>
    <div class="flex flex-col min-h-screen items-center justify-center bg-white">
      <h1 class="text-center mb-5 font-bold text-xl uppercase">book</h1>
      <div
        class="grid grid-cols-1 gap-3 items-center mx-auto max-w-md"
        style="width: 80vw"
      >
        <form @submit.prevent="submit">
          <div>
            <InputLabel for="title" value="Title" />

            <TextInput
              id="title"
              type="text"
              class="mt-1 block w-full"
              v-model="form.title"
              required
              autofocus
            />

            <InputError class="mt-2" :message="form.errors.title" />
          </div>

          <div class="mt-4">
            <InputLabel for="password" value="Password" />

            <TextInput
              id="date"
              type="date"
              class="mt-1 block w-full"
              v-model="form.date"
              required
            />

            <InputError class="mt-2" :message="form.errors.password" />
          </div>
          <PrimaryButton
            class="ms-4 mt-4 ml-auto"
            type="submit"
            :class="{ 'opacity-25': form.processing }"
            :disabled="form.processing"
          >
            Book
          </PrimaryButton>
        </form>
      </div>
    </div>
  </AuthenticatedLayout>
</template>

// resources/js/Pages/Booking/Create.jsx
import React, { useState } from "react";

import AuthenticatedLayout from "@/Layouts/AuthenticatedLayout";
import Checkbox from "@/Components/Checkbox";
import InputError from "@/Components/InputError";
import InputLabel from "@/Components/InputLabel";
import PrimaryButton from "@/Components/PrimaryButton";
import TextInput from "@/Components/TextInput";
import { Head, Link, useForm } from "@inertiajs/react";

export default function Create({ auth }) {
    const { data, setData, post, processing, errors, reset } = useForm({
        email: "",
        title: "",
        name: "",
        date: "",
    });

    const submit = (e) => {
        e.preventDefault();

        post(route("booking.store"));
    };

    return (
        <AuthenticatedLayout user={auth.user}>
            <Head title="Book" />

            <div className="py-12">
                <div className="max-w-4xl mx-auto sm:px-6 lg:px-8">
                    <div className="bg-white overflow-hidden p-6 shadow-sm sm:rounded-lg">
                        <form onSubmit={submit}>
                            <div className="w-full flex flex-col gap-2 md:flex-row">
                                <div className="w-full md:w-1/2">
                                    <InputLabel htmlFor="name" value="Name" />

                                    <TextInput
                                        id="name"
                                        type="text"
                                        name="name"
                                        value={data.name}
                                        className="mt-1 block w-full"
                                        isFocused={true}
                                        onChange={(e) =>
                                            setData("name", e.target.value)
                                        }
                                    />

                                    <InputError
                                        message={errors.name}
                                        className="mt-2"
                                    />
                                </div>

                                <div className="w-full md:w-1/2">
                                    <InputLabel htmlFor="title" value="Title" />

                                    <TextInput
                                        id="title"
                                        type="text"
                                        name="title"
                                        value={data.title}
                                        className="mt-1 block w-full"
                                        isFocused={true}
                                        onChange={(e) =>
                                            setData("title", e.target.value)
                                        }
                                    />

                                    <InputError
                                        message={errors.title}
                                        className="mt-2"
                                    />
                                </div>
                            </div>
                            <div className="w-full flex flex-col gap-2 mt-4 md:flex-row">
                                <div className="w-full md:w-1/2">
                                    <InputLabel htmlFor="email" value="Email" />

                                    <TextInput
                                        id="email"
                                        type="email"
                                        name="email"
                                        value={data.email}
                                        className="mt-1 block w-full"
                                        isFocused={true}
                                        onChange={(e) =>
                                            setData("email", e.target.value)
                                        }
                                    />

                                    <InputError
                                        message={errors.email}
                                        className="mt-2"
                                    />
                                </div>

                                <div className="w-full md:w-1/2">
                                    <InputLabel htmlFor="date" value="Date" />

                                    <TextInput
                                        id="date"
                                        type="date"
                                        name="date"
                                        value={data.date}
                                        className="mt-1 block w-full"
                                        onChange={(e) =>
                                            setData("date", e.target.value)
                                        }
                                    />

                                    <InputError
                                        message={errors.date}
                                        className="mt-2"
                                    />
                                </div>
                            </div>

                            <div className="flex items-center justify-center mt-4">
                                <PrimaryButton
                                    className="ms-4"
                                    disabled={processing}
                                >
                                    Book
                                </PrimaryButton>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </AuthenticatedLayout>
    );
}
